[build-system]
requires = ["setuptools>=61.0", "setuptools_scm[toml]>=8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nbody-sim-RO"
dynamic = ["version"]
description = "N-body physics simulation in Python."
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
    {name = "orzel320", email = "orzellll320@gmail.com"}
]
dependencies = [
    "numpy",
    "numba",
    "pint"
]

[project.optional-dependencies]
vis = [
    "matplotlib",
    "ipympl",
    "k3d",
    "jupyter"
]

test = [
    "pytest",
    "pytest-cov"
]

docs = [
    "mkdocs",
    "mkdocs-material"
]

dev = [
    "nbody-sim[vis,test,docs]"
]

[tool.setuptools_scm]
write_to = "src/nbody_sim/_version.py"
local_scheme = "no-local-version"

[tool.pytest.ini_options]
addopts = "--cov=src/nbody_sim --cov-report=xml --cov-report=term-missing"
testpaths = ["tests"]
pythonpath = ["src"]

[tool.setuptools.packages.find]
where = ["src"]